name = "idkaboutbytes/attributeutils"
version = "1.1.1"
description = "AttributeUtils package for Roblox."
license = "MIT"
authors = ["idkaboutbytes"]
repository = "https://github.com/idkaboutbytes/attributeutils"
includes = [
    "pesde.toml",
    "README.md",
    "CHANGELOG.md",
    "default.project.json",
    "src/**/*.luau",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dependencies]
Brio = { repo = "idkaboutbytes/brio", rev = "v1.2.1" }
Loader = { repo = "idkaboutbytes/loader", rev = "v1.2.2" }
Promise = { repo = "idkaboutbytes/promise", rev = "v2.1.2" }
CancelToken = { repo = "idkaboutbytes/canceltoken", rev = "v1.0.4" }
Maid = { repo = "idkaboutbytes/maid", rev = "v1.1.1" }
Rx = { repo = "idkaboutbytes/rx", rev = "v1.0.3" }
Symbol = { repo = "idkaboutbytes/symbol", rev = "v1.0.1" }
